
extra-deps:
- dimensions-0.3.2.0
- value-supply-0.6
- git: git@github.com:tonyday567/numhask.git
  commit: 0b4dfe39686bf40146f8c3b0018dd1e506723c9e
  subdirs:
    - numhask
    - numhask-prelude
    - numhask-array



resolver: nightly-2018-04-04
