
extra-deps:
- dimensions-0.3.2.0
- value-supply-0.6
- git: git@github.com:tonyday567/numhask.git
  commit: c672a2a499ae79227faa5de6a8d97d76e9e73016
  subdirs:
    - numhask
    - numhask-prelude
    - numhask-array



resolver: nightly-2018-04-04
