
  
packages:
- .
- location:
     git: https://github.com/o1lo01ol1o/numhask-array
     commit: b5c745d24630dfff294d37d1ed93352f724c5792
  extra-dep: true

extra-deps:
- dimensions-0.3.2.0
- tasty-0.12
- value-supply-0.6
resolver: lts-10.4
allow-newer: true
