flags:
  cassava:
    bytestring--lt-0_10_4: false
  time-locale-compat:
    old-locale: false
packages:
- .
extra-deps:
- Glob-0.9.1
- Only-0.1
- abstract-deque-0.3
- abstract-par-0.3.3
- aeson-1.2.3.0
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.1
- attoparsec-0.13.2.0
- base-compat-0.9.3
- base-orphans-0.6
- cassava-0.5.1.0
- cereal-0.5.4.0
- code-page-0.1.3
- colour-2.3.3
- criterion-1.2.4.0
- dlist-0.8.0.3
- erf-2.0.0.0
- exceptions-0.8.3
- hashable-1.2.6.1
- integer-logarithms-1.0.2
- js-flot-0.8.3
- js-jquery-3.2.1
- math-functions-0.2.1.0
- microlens-0.4.8.1
- microlens-th-0.4.1.1
- microstache-1.0.1.1
- monad-par-0.3.4.8
- monad-par-extras-0.3.3
- mtl-2.2.1
- mwc-random-0.13.6.0
- optparse-applicative-0.14.0.0
- parallel-3.2.1.1
- parsec-3.1.11
- primitive-0.6.2.0
- random-1.1
- scientific-0.3.5.2
- semigroups-0.18.3
- statistics-0.14.0.2
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.2
- text-short-0.1.1
- th-abstraction-0.2.6.0
- time-locale-compat-0.1.1.3
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- uuid-types-1.0.3
- value-supply-0.6
- vector-0.12.0.1
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.3.5
- vector-th-unbox-0.2.1.6
resolver: ghc-8.2.1
