
  
packages:
- .
- location:
     git: https://github.com/o1lo01ol1o/numhask-array
     commit: b5c745d24630dfff294d37d1ed93352f724c5792
  extra-dep: true
- location:
     git: https://github.com/atzeus/HMap
     commit: 218519a583e1849c23e0bb476e2245018f9bb8f7
  extra-dep: true

extra-deps:
- dimensions-0.3.2.0
- tasty-0.12
- value-supply-0.6
- data-variant-0.28.0.5
- heterolist-0.2.0.0
- constraint-manip-0.1.1.0
- indextype-0.2.3.0
- polydata-0.1.0.0


resolver: lts-10.4
allow-newer: true
